<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Scalar.AspNetCore"/>
        <PackageReference Include="Ocelot" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Properties\ocelot-configuration\ocelot.global.json" />
      <_ContentIncludedByDefault Remove="Properties\ocelot-configuration\ocelot.json" />
    </ItemGroup>

</Project>
