<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Social.EmailWorker-1d64979c-0ecb-4bcb-a8d4-6f797b64bf8b</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Email/Templates/Register.html"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" />
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="WolverineFx.RabbitMQ" />
        <PackageReference Include="WolverineFx"/>
        <PackageReference Include="WolverineFx.RuntimeCompilation"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\Social.Contracts\Social.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>
</Project>
